#!/usr/bin/env bash
#
# 03-build-test-unikernel.sh — Build the test agent unikernel for Xen
#
# Run as regular user (not root): bash 03-build-test-unikernel.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AGENT_DIR="${SCRIPT_DIR}/test-agent"
BUILD_DIR="${AGENT_DIR}/build"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }

# ─── Check prerequisites ────────────────────────────────────────────────────

if ! command -v kraft &>/dev/null; then
    err "kraft CLI not found. Run 02-install-unikraft.sh first."
fi

# ─── Build using kraft ───────────────────────────────────────────────────────

log "Building test-agent unikernel for Xen x86_64..."
cd "$AGENT_DIR"

kraft build --plat xen --arch x86_64 --log-level debug 2>&1 | tee /tmp/kraft-build.log || {
    warn "kraft build failed. Full log at /tmp/kraft-build.log"
    warn "Last 40 lines:"
    tail -40 /tmp/kraft-build.log
    exit 1
}

# Immediately find and display the .config so we know what kraft compiled
log ""
log "─── Locating .config generated by kraft ───"
FOUND_CONFIG=$(find "$AGENT_DIR" -name ".config" ! -name ".config.*" 2>/dev/null | head -1)
if [[ -z "$FOUND_CONFIG" ]]; then
    FOUND_CONFIG=$(find ~/.cache/kraftkit ~/.local/share/kraftkit 2>/dev/null \
        -name ".config" ! -name ".config.*" | head -1)
fi
if [[ -n "$FOUND_CONFIG" ]]; then
    log "Found: $FOUND_CONFIG"
    log "Key networking/socket symbols:"
    grep -E "^(CONFIG_LIBLWIP|CONFIG_LWIP|CONFIG_LIBPOSIX_SOCKET|CONFIG_LIBPOSIX_FDTAB|CONFIG_LIBUKSCHED|CONFIG_XEN_NETFRONT|CONFIG_LIBUKNETDEV)" \
        "$FOUND_CONFIG" | sort | while IFS= read -r line; do log "  $line"; done
    log "─────────────────────────────────────────────"
    echo "$FOUND_CONFIG" > "${SCRIPT_DIR}/.last-dotconfig"

    # Critical check: liblwip must appear in the build dir
    BUILD_DIR_CHECK="$(dirname "$FOUND_CONFIG")"
    if ls "$BUILD_DIR_CHECK"/liblwip* &>/dev/null 2>&1; then
        log "✓ liblwip compiled (found liblwip*.o in build dir)"
    else
        warn "✗ liblwip NOT found in build dir — lwIP was not compiled!"
        warn "  This means CONFIG_LWIP_SOCKET cannot register AF_INET."
        warn "  The 'libraries: lwip:' section in Kraftfile may not have been used."
        warn "  Check: ls $(dirname "$FOUND_CONFIG")/liblwip*"
    fi
else
    warn "Could not find .config — kraft may store it elsewhere."
    warn "Run: find ~ -name '.config' -newer /tmp/kraft-build.log 2>/dev/null | head -10"
fi

# ─── Find the built image ───────────────────────────────────────────────────

log "Looking for built image..."

# kraft stores builds in .unikraft/build/ — look there first
# Filter out: .config files (text metadata), .dbg (debug), .o (objects), .d (deps)
XEN_IMAGE=$(find "$AGENT_DIR" -path "*/.unikraft/build/*" -name "*_xen-x86_64" \
    -type f ! -name "*.dbg" ! -name "*.o" ! -name "*.d" ! -name ".config*" \
    2>/dev/null | head -1)

if [[ -z "$XEN_IMAGE" ]]; then
    # Fallback: any ELF binary with xen in the name
    XEN_IMAGE=$(find "$AGENT_DIR" -name "*_xen-x86_64" -type f \
        ! -name "*.dbg" ! -name "*.o" ! -name "*.d" ! -name ".config*" \
        2>/dev/null | head -1)
fi

if [[ -z "$XEN_IMAGE" ]]; then
    # Also check kraft's default output location
    XEN_IMAGE=$(find "${HOME}/.local/share/kraftkit" -name "*test*agent*xen*" -type f 2>/dev/null | head -1)
fi

if [[ -z "$XEN_IMAGE" ]]; then
    warn "Could not auto-detect the built image."
    warn "Check the build output above for the image path."
    warn "Common locations:"
    warn "  .unikraft/build/test-agent_xen-x86_64"
    warn "  ~/.local/share/kraftkit/..."
    exit 1
fi

# Verify it's actually an ELF binary, not a config file
FILE_TYPE=$(file "$XEN_IMAGE" 2>/dev/null || echo "unknown")
if ! echo "$FILE_TYPE" | grep -q "ELF"; then
    warn "Found $XEN_IMAGE but it's not an ELF binary: $FILE_TYPE"
    warn "Looking for the actual kernel..."
    # Try harder
    XEN_IMAGE=$(find "$AGENT_DIR" -name "*_xen-x86_64" -type f 2>/dev/null | while read f; do
        file "$f" 2>/dev/null | grep -q ELF && echo "$f" && break
    done)
    if [[ -z "$XEN_IMAGE" ]]; then
        err "Could not find a valid ELF kernel binary."
    fi
fi

IMAGE_SIZE=$(du -h "$XEN_IMAGE" | awk '{print $1}')

log ""
log "═══════════════════════════════════════════════════════════════"
log "  Unikraft test-agent built successfully!"
log "═══════════════════════════════════════════════════════════════"
log ""
log "  Image: $XEN_IMAGE"
log "  Size:  $IMAGE_SIZE"
log ""

# ─── Dump active kconfig to stop guessing what's compiled in ───────────────

DOTCONFIG=$(find "$AGENT_DIR" -path "*/.unikraft/build/.config" -type f 2>/dev/null | head -1)
if [[ -n "$DOTCONFIG" ]]; then
    log "Active kconfig (networking + socket symbols from $DOTCONFIG):"
    echo ""
    grep -E "^CONFIG_(LIBLWIP|LWIP|LIBPOSIX_SOCKET|LIBPOSIX_FDTAB|LIBUKNETDEV|LIBUKSCHED|XEN_NET)" \
        "$DOTCONFIG" | sort | while read line; do echo "    $line"; done
    echo ""
    log "Full .config saved at: $DOTCONFIG"
    log "To see all: grep -v '^#' $DOTCONFIG | grep -v '^$'"
else
    warn "Could not find .config — inspect manually:"
    warn "  find $AGENT_DIR -name '.config' | head -5"
fi

log ""
log "  NEXT STEP: sudo bash 04-test-xen-boot.sh"
log ""

# Save the image path for use by later scripts
echo "$XEN_IMAGE" > "${SCRIPT_DIR}/.last-built-image"
