#!/usr/bin/env bash
#
# 04-test-xen-boot.sh — Boot the test unikernel on Xen directly (no Jitsu)
#
# Run as root: sudo bash 04-test-xen-boot.sh
# Requires: Xen running (post-reboot), unikernel built (step 03)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }

if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root (sudo)"
fi

# ─── Preflight: Verify Xen is running ───────────────────────────────────────

if ! xl info &>/dev/null; then
    err "Xen does not appear to be running. Did you reboot after step 01?"
fi

FREE_MEM=$(xl info | grep free_memory | awk '{print $3}')
log "Xen free memory: ${FREE_MEM}MB"

if [[ "$FREE_MEM" -lt 32 ]]; then
    err "Not enough free Xen memory (${FREE_MEM}MB). Need at least 32MB."
fi

# ─── Locate the unikernel image ─────────────────────────────────────────────

IMAGE_PATH_FILE="${SCRIPT_DIR}/.last-built-image"
if [[ -f "$IMAGE_PATH_FILE" ]]; then
    XEN_IMAGE=$(cat "$IMAGE_PATH_FILE")
else
    # Try common locations
    XEN_IMAGE=$(find "${SCRIPT_DIR}/test-agent" -name "*xen*x86*" -type f 2>/dev/null | head -1)
fi

if [[ -z "${XEN_IMAGE:-}" ]] || [[ ! -f "$XEN_IMAGE" ]]; then
    err "Cannot find unikernel image. Run 03-build-test-unikernel.sh first."
fi

log "Using image: $XEN_IMAGE"

# ─── Detect network bridge ──────────────────────────────────────────────────

BRIDGE="xenbr0"
if ! brctl show "$BRIDGE" &>/dev/null; then
    # Try alternative bridge names
    BRIDGE=$(brctl show 2>/dev/null | awk 'NR>1 && $1 != "" {print $1}' | head -1)
    if [[ -z "$BRIDGE" ]]; then
        warn "No network bridge found. Creating a temporary one..."
        PRIMARY_IF=$(ip route | grep default | awk '{print $5}' | head -1)
        BRIDGE="xenbr0"
        brctl addbr "$BRIDGE" 2>/dev/null || true
        brctl addif "$BRIDGE" "$PRIMARY_IF" 2>/dev/null || true
        ip link set "$BRIDGE" up 2>/dev/null || true
    fi
fi

log "Using bridge: $BRIDGE"

# ─── Assign a static IP for the unikernel ───────────────────────────────────

# Get the bridge network info
BRIDGE_IP=$(ip -4 addr show "$BRIDGE" | grep inet | awk '{print $2}' | cut -d/ -f1 | head -1)
if [[ -z "$BRIDGE_IP" ]]; then
    BRIDGE_IP=$(ip -4 addr show | grep "inet 10\.\|inet 192\.\|inet 172\." | awk '{print $2}' | cut -d/ -f1 | head -1)
fi

# Derive a unikernel IP (use .100 in the same subnet)
UNIKERNEL_IP=$(echo "$BRIDGE_IP" | sed 's/\.[0-9]*$/.100/')
GATEWAY=$(echo "$BRIDGE_IP" | sed 's/\.[0-9]*$/.1/')
NETMASK="255.255.255.0"

log "Unikernel will get IP: $UNIKERNEL_IP (gateway: $GATEWAY)"

# ─── Create Xen domain config ───────────────────────────────────────────────

XEN_CFG="${SCRIPT_DIR}/test-agent.cfg"
VM_NAME="test-agent"

# Clean up any existing domain with this name
xl destroy "$VM_NAME" 2>/dev/null || true
sleep 1

cat > "$XEN_CFG" << EOF
#
# Xen domain configuration for test-agent unikernel
# Auto-generated by 04-test-xen-boot.sh
#

# --- Domain basics ---
name    = "$VM_NAME"
type    = "pvh"
kernel  = "$XEN_IMAGE"

# --- Resources ---
memory  = 32
vcpus   = 1

# --- Network ---
vif     = ['bridge=$BRIDGE']

# --- Boot command line ---
# Pass network config to the unikernel via command line
# Unikraft lwIP reads these for static IP configuration
cmdline = "netdev.ipv4_addr=$UNIKERNEL_IP netdev.ipv4_gw_addr=$GATEWAY netdev.ipv4_subnet_mask=$NETMASK --"

# --- Console ---
# Enable Xen console for debugging
serial  = "pty"
EOF

log "Xen config written to $XEN_CFG"

# ─── Boot the unikernel ─────────────────────────────────────────────────────

log ""
log "Booting unikernel..."
BOOT_START=$(date +%s%N)

xl create "$XEN_CFG" 2>&1

BOOT_END=$(date +%s%N)
BOOT_MS=$(( (BOOT_END - BOOT_START) / 1000000 ))

log "xl create took ${BOOT_MS}ms"

# ─── Verify it's running ────────────────────────────────────────────────────

sleep 1

log ""
log "Domain list:"
xl list

DOMAIN_ID=$(xl domid "$VM_NAME" 2>/dev/null || echo "")
if [[ -z "$DOMAIN_ID" ]]; then
    err "Domain $VM_NAME not found. Check xl console $VM_NAME for errors."
fi

log "Domain ID: $DOMAIN_ID"

# ─── Check console output ───────────────────────────────────────────────────

log ""
log "Console output (first 5 seconds):"
timeout 5 xl console "$VM_NAME" 2>/dev/null || true
log ""

# ─── Test connectivity ───────────────────────────────────────────────────────

log "Waiting for unikernel network to come up..."
for i in {1..30}; do
    if ping -c 1 -W 1 "$UNIKERNEL_IP" &>/dev/null; then
        log "Unikernel is responding to ping!"
        break
    fi
    if [[ $i -eq 30 ]]; then
        warn "Unikernel not responding to ping after 30s."
        warn "This may be normal if ICMP is not supported."
        warn "Trying HTTP instead..."
    fi
    sleep 1
done

# Test HTTP
log "Testing HTTP endpoint..."
HTTP_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
    "http://${UNIKERNEL_IP}:8080/health" --connect-timeout 5 2>/dev/null || echo "000")

if [[ "$HTTP_RESPONSE" == "200" ]]; then
    log "HTTP health check: 200 OK"
    BODY=$(curl -s "http://${UNIKERNEL_IP}:8080/health" --connect-timeout 5 2>/dev/null)
    log "Response: $BODY"
else
    warn "HTTP health check returned: $HTTP_RESPONSE"
    warn "The unikernel may need DHCP or different network config."
    warn "Debug with: xl console $VM_NAME"
fi

# ─── Benchmark ───────────────────────────────────────────────────────────────

log ""
log "═══════════════════════════════════════════════════════════════"
log "  Test Boot Results:"
log "═══════════════════════════════════════════════════════════════"
log ""
log "  Domain:      $VM_NAME (ID: $DOMAIN_ID)"
log "  Boot time:   ${BOOT_MS}ms (xl create latency)"
log "  Memory:      32MB"

MEM_ACTUAL=$(xl list | grep "$VM_NAME" | awk '{print $3}')
log "  Memory used: ${MEM_ACTUAL}MB (from xl list)"
log "  IP:          $UNIKERNEL_IP"
log "  HTTP:        $HTTP_RESPONSE"
log ""

# ─── Cleanup ─────────────────────────────────────────────────────────────────

log "Cleaning up — destroying test domain..."
xl destroy "$VM_NAME" 2>/dev/null || true
log "Domain destroyed."

log ""
log "  NEXT STEP: bash 05-install-jitsu.sh"
log ""

# Save config for Jitsu step
echo "$UNIKERNEL_IP" > "${SCRIPT_DIR}/.unikernel-ip"
echo "$XEN_IMAGE" > "${SCRIPT_DIR}/.last-built-image"
echo "$BRIDGE" > "${SCRIPT_DIR}/.bridge"
