#!/usr/bin/env bash
#
# 04-test-xen-boot.sh — Boot the test unikernel on Xen directly (no Jitsu)
#
# Run as root: sudo bash 04-test-xen-boot.sh
# Requires: Xen running (post-reboot), unikernel built (step 03)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }

if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root (sudo)"
fi

# ─── Preflight: Verify Xen is running ───────────────────────────────────────

if ! xl info &>/dev/null; then
    err "Xen does not appear to be running. Did you reboot after step 01?"
fi

FREE_MEM=$(xl info | grep free_memory | awk '{print $3}')
log "Xen free memory: ${FREE_MEM}MB"

if [[ "$FREE_MEM" -lt 32 ]]; then
    err "Not enough free Xen memory (${FREE_MEM}MB). Need at least 32MB."
fi

# ─── Locate the unikernel image ─────────────────────────────────────────────

IMAGE_PATH_FILE="${SCRIPT_DIR}/.last-built-image"
XEN_IMAGE=""

# Check saved path from build step
if [[ -f "$IMAGE_PATH_FILE" ]]; then
    SAVED=$(cat "$IMAGE_PATH_FILE")
    if [[ -f "$SAVED" ]] && file "$SAVED" 2>/dev/null | grep -q ELF; then
        XEN_IMAGE="$SAVED"
    fi
fi

# Search in .unikraft/build/ (where kraft actually puts the binary)
if [[ -z "$XEN_IMAGE" ]]; then
    XEN_IMAGE=$(find "${SCRIPT_DIR}/test-agent" -path "*/.unikraft/build/*" \
        -name "*_xen-x86_64" -type f ! -name "*.dbg" ! -name ".config*" \
        2>/dev/null | head -1)
fi

# Verify it's an ELF
if [[ -n "${XEN_IMAGE:-}" ]] && [[ -f "$XEN_IMAGE" ]]; then
    if ! file "$XEN_IMAGE" 2>/dev/null | grep -q ELF; then
        warn "$XEN_IMAGE is not an ELF binary, searching for correct one..."
        XEN_IMAGE=""
    fi
fi

if [[ -z "${XEN_IMAGE:-}" ]] || [[ ! -f "$XEN_IMAGE" ]]; then
    err "Cannot find unikernel ELF image. Run 03-build-test-unikernel.sh first."
fi

log "Using image: $XEN_IMAGE"
log "  Type: $(file "$XEN_IMAGE" | cut -d: -f2)"

# ─── Detect network bridge ──────────────────────────────────────────────────
#
# We use a PRIVATE bridge (ukbr0, 10.0.0.1/24) — NOT the public-IP bridge.
# Vultr/cloud providers use MAC anti-spoofing and silently drop traffic from
# unregistered IPs on the public bridge.  Using a private subnet + NAT avoids
# this entirely.  Run 01c-setup-unikernel-bridge.sh first.

BRIDGE_FILE="${SCRIPT_DIR}/.unikernel-bridge"
GW_FILE="${SCRIPT_DIR}/.unikernel-gateway"

if [[ -f "$BRIDGE_FILE" ]]; then
    BRIDGE=$(cat "$BRIDGE_FILE")
else
    BRIDGE="ukbr0"
fi

# Ensure the private bridge exists
if ! ip link show "$BRIDGE" &>/dev/null; then
    err "Private bridge '$BRIDGE' not found.\n" \
        "Run first:  sudo bash setup/01c-setup-unikernel-bridge.sh"
fi

log "Using bridge: $BRIDGE (private unikernel network)"

# ─── Private network addressing ──────────────────────────────────────────────
# dom0 is 10.0.0.1 (gateway)  — set by 01c-setup-unikernel-bridge.sh
# Unikernel gets 10.0.0.100   — static, no DHCP needed

if [[ -f "$GW_FILE" ]]; then
    GATEWAY=$(cat "$GW_FILE")
else
    GATEWAY="10.0.0.1"
fi

CIDR="24"
UNIKERNEL_IP="10.0.0.100"

log "Network config:"
log "  Bridge:         $BRIDGE"
log "  dom0 (gateway): $GATEWAY"
log "  Unikernel IP:   $UNIKERNEL_IP/$CIDR"
log "  (dom0 NATs unikernel traffic to the internet via xenbr0)"

# ─── Create Xen domain config ───────────────────────────────────────────────

XEN_CFG="${SCRIPT_DIR}/test-agent.cfg"
VM_NAME="test-agent"

# Clean up any existing domain with this name
xl destroy "$VM_NAME" 2>/dev/null || true
sleep 1

# Unikraft cmdline format: netdev.ip=<IP/CIDR>:<GW>:<DNS>
# See lib/uknetdev/netdev.c — UK_LIBPARAM_PARAM_ARR_ALIAS(ip, ...)
UK_NETDEV_IP="${UNIKERNEL_IP}/${CIDR}:${GATEWAY}:8.8.8.8"

cat > "$XEN_CFG" << EOF
#
# Xen domain configuration for test-agent unikernel
# Auto-generated by 04-test-xen-boot.sh
#

# --- Domain basics ---
name    = "$VM_NAME"
type    = "pv"
kernel  = "$XEN_IMAGE"

# --- Resources ---
memory  = 64
vcpus   = 1

# --- Network ---
vif     = ['bridge=$BRIDGE']

# --- Boot command line ---
# Unikraft libukboot parses cmdline before '--', passing everything after as app argv.
# netdev.ip0= sets static IP/CIDR:GW:DNS on the first network device.
# No trailing '--' so all params are interpreted as boot params (not app argv).
cmdline = "netdev.ip0=$UK_NETDEV_IP"

# --- Console ---
# Enable Xen console for debugging
serial  = "pty"
EOF

log "Xen config written to $XEN_CFG"
log "  cmdline: netdev.ip0=$UK_NETDEV_IP"

# ─── Boot the unikernel ─────────────────────────────────────────────────────

log ""
log "Booting unikernel..."
BOOT_START=$(date +%s%N)

xl create "$XEN_CFG" 2>&1

BOOT_END=$(date +%s%N)
BOOT_MS=$(( (BOOT_END - BOOT_START) / 1000000 ))

log "xl create took ${BOOT_MS}ms"

# ─── Verify it's running ────────────────────────────────────────────────────

sleep 1

log ""
log "Domain list:"
xl list

DOMAIN_ID=$(xl domid "$VM_NAME" 2>/dev/null || echo "")
if [[ -z "$DOMAIN_ID" ]]; then
    err "Domain $VM_NAME not found. Check xl console $VM_NAME for errors."
fi

log "Domain ID: $DOMAIN_ID"

# ─── Show vif attachment (important: proves bridge wiring) ──────────────────

log ""
log "Network interface status:"
xl network-list "$VM_NAME" 2>/dev/null || warn "xl network-list not available"
log ""
log "Bridge members ($BRIDGE should list a vif here):"
brctl show "$BRIDGE" 2>/dev/null || true
log ""

log ""
log "Checking for unikernel boot messages..."
# Capture guest console output (with timeout so it doesn't hang)
# xl console is interactive, so we use a timeout + background approach
log "--- Guest console (first 5 seconds) ---"
timeout 8 xl console "$VM_NAME" 2>/dev/null &
CONSOLE_PID=$!
sleep 5
kill $CONSOLE_PID 2>/dev/null || true
wait $CONSOLE_PID 2>/dev/null || true
log "--- End guest console ---"
log ""
log "(For live console, run in ANOTHER SSH session:)"
log "  sudo xl console $VM_NAME"
log "  (Press Ctrl+] to detach without killing the VM)"
log ""

# unikernel now probes socket() every 2s for up to 60s and prints errno each
# time — no upfront sleep needed. We poll HTTP directly from dom0.
log "Polling HTTP until unikernel is ready (max 75s)..."
HTTP_RESPONSE="000"
for i in $(seq 1 75); do
    CODE=$(curl -s -o /tmp/uk_response.txt -w "%{http_code}" \
        "http://${UNIKERNEL_IP}:8080/health" \
        --connect-timeout 2 --max-time 3 2>/dev/null || echo "000")
    if [[ "$CODE" == "200" ]]; then
        HTTP_RESPONSE="200"
        log "HTTP 200 OK after ${i}s!"
        break
    fi
    printf "\r[+] %2ds — HTTP=%s, ping=%s..." \
        "$i" "$CODE" \
        "$(ping -c1 -W1 $UNIKERNEL_IP &>/dev/null && echo OK || echo -)"
    sleep 1
done
echo ""

if [[ "$HTTP_RESPONSE" == "200" ]]; then
    log "HTTP health check: 200 OK"
    log "Response: $(cat /tmp/uk_response.txt 2>/dev/null)"
else
    warn "HTTP health check returned: $HTTP_RESPONSE"
    warn ""
    warn "─── Console snapshot (errno output shows WHY socket() is failing) ───"
    timeout 6 xl console "$VM_NAME" 2>/dev/null &
    CONSOLE_PID2=$!
    sleep 4
    kill $CONSOLE_PID2 2>/dev/null || true
    wait $CONSOLE_PID2 2>/dev/null || true
    warn "─── End snapshot ───"
    warn ""
fi

# ─── Benchmark ───────────────────────────────────────────────────────────────

log ""
log "═══════════════════════════════════════════════════════════════"
log "  Test Boot Results:"
log "═══════════════════════════════════════════════════════════════"
log ""
log "  Domain:      $VM_NAME (ID: $DOMAIN_ID)"
log "  Boot time:   ${BOOT_MS}ms (xl create latency)"
log "  Memory:      32MB"

MEM_ACTUAL=$(xl list | grep "$VM_NAME" | awk '{print $3}')
log "  Memory used: ${MEM_ACTUAL}MB (from xl list)"
log "  IP:          $UNIKERNEL_IP"
log "  HTTP:        $HTTP_RESPONSE"
log ""

# ─── Cleanup ─────────────────────────────────────────────────────────────────

if [[ "$HTTP_RESPONSE" == "200" ]]; then
    log "Test passed! Cleaning up — destroying test domain..."
    xl destroy "$VM_NAME" 2>/dev/null || true
    log "Domain destroyed."
else
    warn ""
    warn "Networking not working yet. Keeping domain ALIVE for debugging."
    warn ""
    warn "Debug commands (run in another SSH session):"
    warn "  sudo xl console $VM_NAME          # see app output"
    warn "  sudo xl network-list $VM_NAME     # check vif"
    warn "  brctl show $BRIDGE                # check bridge members"
    warn "  ip addr show $BRIDGE              # verify 10.0.0.1/24 on bridge"
    warn "  ping $UNIKERNEL_IP                # test connectivity from dom0"
    warn ""
    warn "If bridge has no IP: sudo bash setup/01c-setup-unikernel-bridge.sh"
    warn "When done:  sudo xl destroy $VM_NAME"
fi

log ""
log "  NEXT STEP: bash 05-install-jitsu.sh"
log ""

# Save config for Jitsu step
echo "$UNIKERNEL_IP" > "${SCRIPT_DIR}/.unikernel-ip"
echo "$XEN_IMAGE" > "${SCRIPT_DIR}/.last-built-image"
echo "$BRIDGE"        > "${SCRIPT_DIR}/.bridge"
echo "$UNIKERNEL_IP" > "${SCRIPT_DIR}/.unikernel-ip-last"
